package com.ericg.jichat.ui.theme

import androidx.compose.ui.graphics.Color
/** Brown-based Theme*/
val md_theme_light_primary = Color(0xFF855400)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffddb3)
val md_theme_light_onPrimaryContainer = Color(0xFF2a1700)
val md_theme_light_secondary = Color(0xFF705b40)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFfbdebc)
val md_theme_light_onSecondaryContainer = Color(0xFF271905)
val md_theme_light_tertiary = Color(0xFF53643e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFd6eaba)
val md_theme_light_onTertiaryContainer = Color(0xFF111f03)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1f1b16)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1f1b16)
val md_theme_light_surfaceVariant = Color(0xFFf0e0d0)
val md_theme_light_onSurfaceVariant = Color(0xFF504539)
val md_theme_light_outline = Color(0xFF817568)
val md_theme_light_inverseOnSurface = Color(0xFFf9efe7)
val md_theme_light_inverseSurface = Color(0xFF35302a)
val md_theme_light_inversePrimary = Color(0xFFffb954)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffb954)
val md_theme_dark_onPrimary = Color(0xFF462a00)
val md_theme_dark_primaryContainer = Color(0xFF643f00)
val md_theme_dark_onPrimaryContainer = Color(0xFFffddb3)
val md_theme_dark_secondary = Color(0xFFdec2a2)
val md_theme_dark_onSecondary = Color(0xFF3e2d16)
val md_theme_dark_secondaryContainer = Color(0xFF56432a)
val md_theme_dark_onSecondaryContainer = Color(0xFFfbdebc)
val md_theme_dark_tertiary = Color(0xFFbacda0)
val md_theme_dark_onTertiary = Color(0xFF263514)
val md_theme_dark_tertiaryContainer = Color(0xFF3c4c29)
val md_theme_dark_onTertiaryContainer = Color(0xFFd6eaba)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1f1b16)
val md_theme_dark_onBackground = Color(0xFFebe1d9)
val md_theme_dark_surface = Color(0xFF1f1b16)
val md_theme_dark_onSurface = Color(0xFFebe1d9)
val md_theme_dark_surfaceVariant = Color(0xFF504539)
val md_theme_dark_onSurfaceVariant = Color(0xFFd4c4b4)
val md_theme_dark_outline = Color(0xFF9c8e80)
val md_theme_dark_inverseOnSurface = Color(0xFF1f1b16)
val md_theme_dark_inverseSurface = Color(0xFFebe1d9)
val md_theme_dark_inversePrimary = Color(0xFF855400)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFFfcaf3e)
val error = Color(0xFFba1b1b)
